name: tekartik_io_utils
version: 0.2.1
description: Tekartik IO utilities
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/io_utils.dart
environment:
  sdk: '>=1.24.3 <2.0.0'
dependencies:
  pub_semver: any
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
    version: '>=0.5.0'
  process_run: any

    version: '>=0.5.1'
dev_dependencies:
  test: '>=0.12.34'
  dev_test: '>=0.11.0'

