name: tekartik_io_utils
version: 0.4.0
description: Tekartik IO utilities
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/io_utils.dart
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  pub_semver: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.5.1'
  process_run: any
dev_dependencies:
  test: '>=0.12.34'
  dev_test: '>=0.12.0'
  build_runner: '>=0.9.0'
  build_test:

