name: tekartik_io_utils
version: 0.8.0
description: Tekartik IO utilities
homepage: https://github.com/tekartik/io_utils.dart
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  pub_semver: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.9'
  process_run: '>=0.10.0+1'
  path:
dev_dependencies:
  test: '>1.2.0'
  build_runner: '>=0.9.0'
  build_test:
  dev_build: '>=1.0.0'
