name: tekartik_io_utils
version: 0.7.0
description: Tekartik IO utilities

homepage: https://github.com/tekartik/io_utils.dart
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  pub_semver: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.9.9'
  process_run: '>=0.10.0+1'
  path:
dev_dependencies:
  pedantic: '>=1.4.0'
  test: '>1.2.0'
  dev_test: '>=0.12.0'
  build_runner: '>=0.9.0'
  build_test: