name: tekartik_io_utils
version: 0.5.0
description: Tekartik IO utilities
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/io_utils.dart
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  pub_semver: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.6.5'
  tekartik_platform_io:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart2
    version: '>=0.1.1'
  process_run: any
dev_dependencies:
  pedantic: '>=1.4.0'
  test: '>1.2.0'
  dev_test: '>=0.12.0'
  build_runner: '>=0.9.0'
  build_test:

