name: tekartik_io_utils
version: 0.2.1
description: Tekartik IO utilities
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/io_utils.dart
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
    version: '>=0.5.0'
  process_run: any

dev_dependencies:
  test: '>=0.12.15'
  dev_test: '>=0.9.3'

