name: tekartik_io_utils
version: 0.8.0
description: Tekartik IO utilities
homepage: https://github.com/tekartik/io_utils.dart
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  pub_semver: ">=2.1.4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.9'
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
dev_dependencies:
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test:
  dev_build: ">=1.1.2"
